services:
  pye:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: psql
      POSTGRES_DB: pyedb
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
